### ISSUE TITLE
Compilation Error in master branch using erl22.2

### ISSUE THREAD

**Issue by xmppjingle** [erlcloud/erlcloud#751]
Compilation fails with:
```
===> Compiling _build/default/lib/erlcloud/src/erlcloud_s3.erl failed
erlcloud_s3: function '-encode_public_access_block/1-lc$^0/1-0-'/1+14:
  Internal consistency check failed - please report this bug.
  Instruction: {call,1,{f,692}}
  Error:       {bad_arg_type,{x,0},
                             {tuple,2,#{}},
                             {tuple,2,#{{integer,2} => bool}}}:
```

**Comment by motobob** [comment]
works fine on 22.3, 21, 24, 25 build jobs are set to check it here.
looks the function encode_public_access_block/1 I also see no issues.

do you have a clean 22.2 from kerl?

**Comment by motobob** [comment]
cannot reproduce. please explain how and we will address. PR is also welcome,
